In [1]:
import numpy as np

# Zadanie 1.1

In [2]:
np.random.seed(123)
x = np.random.uniform(-4, 4, 30)
x

array([ 1.57175348, -1.71088532, -2.18518837,  0.41051815,  1.75575176,
       -0.61514832,  3.84611359,  1.47863791, -0.15254479, -0.86305985,
       -1.25457587,  1.83239766, -0.49142204, -3.52257683, -0.81564596,
        1.90396325, -2.54006616, -2.59638595,  0.25241099,  0.2546207 ,
        1.07520767,  2.79545435,  1.7956426 ,  0.88818809,  1.77954706,
       -1.41632869, -1.10569076, -2.17389415, -1.65028763,  1.04780899])

## A. Wszystkie wartości ze zbioru [-2,-1] i [1,2]

In [3]:
((x>=-2) & (x<=-1)) | ((x>=1) & (x<=2))

array([ True,  True, False, False,  True, False, False,  True, False,
       False,  True,  True, False, False, False,  True, False, False,
       False, False,  True, False,  True, False,  True,  True,  True,
       False,  True,  True])

In [4]:
x[((x>=-2) & (x<=-1)) | ((x>=1) & (x<=2))]

array([ 1.57175348, -1.71088532,  1.75575176,  1.47863791, -1.25457587,
        1.83239766,  1.90396325,  1.07520767,  1.7956426 ,  1.77954706,
       -1.41632869, -1.10569076, -1.65028763,  1.04780899])

In [5]:
np.r_[x[(x>=-2) & (x<=-1)],  x[(x>=1) & (x<=2)]]

array([-1.71088532, -1.25457587, -1.41632869, -1.10569076, -1.65028763,
        1.57175348,  1.75575176,  1.47863791,  1.83239766,  1.90396325,
        1.07520767,  1.7956426 ,  1.77954706,  1.04780899])

## B. Wypisz na ekran liczbę wszystkich wartości nieujemnych

In [6]:
np.sum(np.array([True, False, True]))

2

In [7]:
len(x[x >= 0])

15

In [8]:
x[x >= 0].size

15

In [9]:
np.sum(x >= 0)

15

# C. Wyznacz średnią arytmetyczna wartości bezwzględnych elementów

In [10]:
np.abs(x)

array([1.57175348, 1.71088532, 2.18518837, 0.41051815, 1.75575176,
       0.61514832, 3.84611359, 1.47863791, 0.15254479, 0.86305985,
       1.25457587, 1.83239766, 0.49142204, 3.52257683, 0.81564596,
       1.90396325, 2.54006616, 2.59638595, 0.25241099, 0.2546207 ,
       1.07520767, 2.79545435, 1.7956426 , 0.88818809, 1.77954706,
       1.41632869, 1.10569076, 2.17389415, 1.65028763, 1.04780899])

In [11]:
np.mean(np.abs(x))

1.5260572308400788

In [12]:
abs(x)

array([1.57175348, 1.71088532, 2.18518837, 0.41051815, 1.75575176,
       0.61514832, 3.84611359, 1.47863791, 0.15254479, 0.86305985,
       1.25457587, 1.83239766, 0.49142204, 3.52257683, 0.81564596,
       1.90396325, 2.54006616, 2.59638595, 0.25241099, 0.2546207 ,
       1.07520767, 2.79545435, 1.7956426 , 0.88818809, 1.77954706,
       1.41632869, 1.10569076, 2.17389415, 1.65028763, 1.04780899])

In [13]:
np.mean(x)

-0.01352281479601792

In [14]:
sum(x)

-0.4056844438805367

In [15]:
np.sum(np.abs(x))/x.size

1.5260572308400788

## D. Największą i najmniejszą wartość

In [16]:
np.minimum(x,x)

array([ 1.57175348, -1.71088532, -2.18518837,  0.41051815,  1.75575176,
       -0.61514832,  3.84611359,  1.47863791, -0.15254479, -0.86305985,
       -1.25457587,  1.83239766, -0.49142204, -3.52257683, -0.81564596,
        1.90396325, -2.54006616, -2.59638595,  0.25241099,  0.2546207 ,
        1.07520767,  2.79545435,  1.7956426 ,  0.88818809,  1.77954706,
       -1.41632869, -1.10569076, -2.17389415, -1.65028763,  1.04780899])

In [17]:
np.min(x)

-3.522576827123453

In [19]:
np.max(x)

3.846113587076924

## E. Wyznacz wartość najbliższą i najdalsza od 0 (zachowując jej znak)

In [20]:
np.abs(3-5)

2

In [21]:
# oblicz odległości każdego elementu od 0
odleglosci = np.abs(x-0)
odleglosci
# wybierz największą i najmniejszą odległość
np.argmin(odleglosci), np.argmax(odleglosci)
# zwróć liczby, które nam dały te właśnie odległości
x[np.argmin(odleglosci)], x[np.argmax(odleglosci)]

(-0.15254478812511252, 3.846113587076924)

In [22]:
x==np.min(odleglosci)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [23]:
x[np.abs(x)==np.min(odleglosci)]

array([-0.15254479])

In [24]:
np.abs(x)==np.max(odleglosci)

array([False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [25]:
x[odleglosci==np.max(odleglosci)]

array([3.84611359])

## F. Wariant z 2

In [26]:
odleglosci = np.abs(x-2)
x[np.argmin(odleglosci)], x[np.argmax(odleglosci)]
x[np.r_[np.argmin(odleglosci), np.argmax(odleglosci)]]

array([ 1.90396325, -3.52257683])

## G. Wypisz na ekran część ułamkową wszystkich elementów

In [27]:
1.234 -> 1
-2.453 -> -2
-2.79 -> -2
1.79 -> 1

SyntaxError: invalid syntax (<ipython-input-27-7c7ce20beba1>, line 1)

In [28]:
1.234 -> 0.234
-2.453 -> -0.453
-2.79 -> -0.79
1.79 -> 0.79

SyntaxError: invalid syntax (<ipython-input-28-4da8fc7c5530>, line 1)

In [29]:
fraction
decimal part
truncate

SyntaxError: invalid syntax (<ipython-input-29-fd86d01f0f96>, line 2)

In [30]:
x

array([ 1.57175348, -1.71088532, -2.18518837,  0.41051815,  1.75575176,
       -0.61514832,  3.84611359,  1.47863791, -0.15254479, -0.86305985,
       -1.25457587,  1.83239766, -0.49142204, -3.52257683, -0.81564596,
        1.90396325, -2.54006616, -2.59638595,  0.25241099,  0.2546207 ,
        1.07520767,  2.79545435,  1.7956426 ,  0.88818809,  1.77954706,
       -1.41632869, -1.10569076, -2.17389415, -1.65028763,  1.04780899])

In [31]:
x.astype(int)

array([ 1, -1, -2,  0,  1,  0,  3,  1,  0,  0, -1,  1,  0, -3,  0,  1, -2,
       -2,  0,  0,  1,  2,  1,  0,  1, -1, -1, -2, -1,  1])

In [32]:
x - x.astype(int)

array([ 0.57175348, -0.71088532, -0.18518837,  0.41051815,  0.75575176,
       -0.61514832,  0.84611359,  0.47863791, -0.15254479, -0.86305985,
       -0.25457587,  0.83239766, -0.49142204, -0.52257683, -0.81564596,
        0.90396325, -0.54006616, -0.59638595,  0.25241099,  0.2546207 ,
        0.07520767,  0.79545435,  0.7956426 ,  0.88818809,  0.77954706,
       -0.41632869, -0.10569076, -0.17389415, -0.65028763,  0.04780899])

In [33]:
np.modf(x)[0]

array([ 0.57175348, -0.71088532, -0.18518837,  0.41051815,  0.75575176,
       -0.61514832,  0.84611359,  0.47863791, -0.15254479, -0.86305985,
       -0.25457587,  0.83239766, -0.49142204, -0.52257683, -0.81564596,
        0.90396325, -0.54006616, -0.59638595,  0.25241099,  0.2546207 ,
        0.07520767,  0.79545435,  0.7956426 ,  0.88818809,  0.77954706,
       -0.41632869, -0.10569076, -0.17389415, -0.65028763,  0.04780899])

In [34]:
x-np.trunc(x)

array([ 0.57175348, -0.71088532, -0.18518837,  0.41051815,  0.75575176,
       -0.61514832,  0.84611359,  0.47863791, -0.15254479, -0.86305985,
       -0.25457587,  0.83239766, -0.49142204, -0.52257683, -0.81564596,
        0.90396325, -0.54006616, -0.59638595,  0.25241099,  0.2546207 ,
        0.07520767,  0.79545435,  0.7956426 ,  0.88818809,  0.77954706,
       -0.41632869, -0.10569076, -0.17389415, -0.65028763,  0.04780899])

## H. Interpolacja liniowa

In [35]:
x

array([ 1.57175348, -1.71088532, -2.18518837,  0.41051815,  1.75575176,
       -0.61514832,  3.84611359,  1.47863791, -0.15254479, -0.86305985,
       -1.25457587,  1.83239766, -0.49142204, -3.52257683, -0.81564596,
        1.90396325, -2.54006616, -2.59638595,  0.25241099,  0.2546207 ,
        1.07520767,  2.79545435,  1.7956426 ,  0.88818809,  1.77954706,
       -1.41632869, -1.10569076, -2.17389415, -1.65028763,  1.04780899])

In [36]:
# znajdz najmniejsza wartosc w x
x_min = np.min(x)
# znajdz najwieksza wartosc w x
x_max = np.max(x)
# zaimplementuj wzor
(x-x_min)/(x_max-x_min) * (1 - (-1)) + (-1)

array([ 0.38269625, -0.50827314, -0.63700783,  0.06751533,  0.43263682,
       -0.21086968,  1.        ,  0.35742295, -0.08531046, -0.2781575 ,
       -0.38442224,  0.45343994, -0.17728806, -1.        , -0.26528848,
        0.47286418, -0.73332828, -0.74861452,  0.02460209,  0.02520185,
        0.24792446,  0.71483149,  0.44346393,  0.19716386,  0.4390953 ,
       -0.42832498, -0.34401205, -0.63394237, -0.49182579,  0.24048795])

## I. średnią wartość kwadratów liczb większych od 3 lub mniejszych od -2

In [37]:
np.mean(x[(x > 3) | (x < -2)]**2)

8.315859553206058

## K. Utwórz wektor napisów y o długości takiej samej, jaką ma x, dla ktorego yi przyjmuje wartosc 'nieujemna', jesli xi jest nieujemne oraz 'ujemna' w przeciwnym przypadku,

In [38]:
x

array([ 1.57175348, -1.71088532, -2.18518837,  0.41051815,  1.75575176,
       -0.61514832,  3.84611359,  1.47863791, -0.15254479, -0.86305985,
       -1.25457587,  1.83239766, -0.49142204, -3.52257683, -0.81564596,
        1.90396325, -2.54006616, -2.59638595,  0.25241099,  0.2546207 ,
        1.07520767,  2.79545435,  1.7956426 ,  0.88818809,  1.77954706,
       -1.41632869, -1.10569076, -2.17389415, -1.65028763,  1.04780899])

In [39]:
np.where(warunek, wektor1, wektor2)

NameError: name 'warunek' is not defined

In [40]:
np.where(x<0,"ujemna","nieujemna")

array(['nieujemna', 'ujemna', 'ujemna', 'nieujemna', 'nieujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'ujemna', 'ujemna', 'ujemna',
       'nieujemna', 'ujemna', 'ujemna', 'ujemna', 'nieujemna', 'ujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'nieujemna', 'nieujemna',
       'nieujemna', 'nieujemna', 'nieujemna', 'ujemna', 'ujemna',
       'ujemna', 'ujemna', 'nieujemna'], dtype='<U9')

### podejście 3

In [41]:
np.empty(30)

array([1.57175348, 1.71088532, 2.18518837, 0.41051815, 1.75575176,
       0.61514832, 3.84611359, 1.47863791, 0.15254479, 0.86305985,
       1.25457587, 1.83239766, 0.49142204, 3.52257683, 0.81564596,
       1.90396325, 2.54006616, 2.59638595, 0.25241099, 0.2546207 ,
       1.07520767, 2.79545435, 1.7956426 , 0.88818809, 1.77954706,
       1.41632869, 1.10569076, 2.17389415, 1.65028763, 1.04780899])

In [42]:
np.where(x<0)

(array([ 1,  2,  5,  8,  9, 10, 12, 13, 14, 16, 17, 25, 26, 27, 28]),)

In [43]:
y = np.repeat("nieujemna", x.size) #np.empty(x.size).astype(str) #
# y[np.where(x>=0)] = "nieujemna"
y[np.where(x<0)] = "ujemna"
y

array(['nieujemna', 'ujemna', 'ujemna', 'nieujemna', 'nieujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'ujemna', 'ujemna', 'ujemna',
       'nieujemna', 'ujemna', 'ujemna', 'ujemna', 'nieujemna', 'ujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'nieujemna', 'nieujemna',
       'nieujemna', 'nieujemna', 'nieujemna', 'ujemna', 'ujemna',
       'ujemna', 'ujemna', 'nieujemna'], dtype='<U9')

### podejśćie 2

In [44]:
np.array(["ujemna", "nieujemna"])[odpowiednio zaindeksowac]

SyntaxError: invalid syntax (<ipython-input-44-bfb7f99c51fa>, line 1)

In [45]:
np.array(["ujemna", "nieujemna"])[np.array([0,0,1,1,0,1])]

array(['ujemna', 'ujemna', 'nieujemna', 'nieujemna', 'ujemna',
       'nieujemna'], dtype='<U9')

In [46]:
np.array(["ujemna", "nieujemna"])[np.array([False,False,True,True,False,True]).astype(int)]

array(['ujemna', 'ujemna', 'nieujemna', 'nieujemna', 'ujemna',
       'nieujemna'], dtype='<U9')

In [47]:
np.array(["nieujemna", "ujemna"])[(x<0).astype(int)]

array(['nieujemna', 'ujemna', 'ujemna', 'nieujemna', 'nieujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'ujemna', 'ujemna', 'ujemna',
       'nieujemna', 'ujemna', 'ujemna', 'ujemna', 'nieujemna', 'ujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'nieujemna', 'nieujemna',
       'nieujemna', 'nieujemna', 'nieujemna', 'ujemna', 'ujemna',
       'ujemna', 'ujemna', 'nieujemna'], dtype='<U9')

## jego minimum i maksimum,ale nie używając funkcji min i max

In [48]:
np.sort(x)[[0,-1]]

array([-3.52257683,  3.84611359])

## O. Utwórz wektor liczbowy y o długosci takiej samej, jaką ma x, dla którego yi przyjmuje wartość k+0.5 wtedy i tylko wtedy, gdy xi należy do [k, k+1), gdzie k to liczba całkowita (prosty histogram).

In [49]:
np.floor(x)+0.5

array([ 1.5, -1.5, -2.5,  0.5,  1.5, -0.5,  3.5,  1.5, -0.5, -0.5, -1.5,
        1.5, -0.5, -3.5, -0.5,  1.5, -2.5, -2.5,  0.5,  0.5,  1.5,  2.5,
        1.5,  0.5,  1.5, -1.5, -1.5, -2.5, -1.5,  1.5])

# Zadanie 2

In [50]:
x = np.array([10,9,8,7,6,5,4,3,2,1])
y = np.array([1,2,3,4,5,6,7,8,9,10])

In [51]:
x_mean = np.mean(x)
y_mean = np.mean(y)

In [52]:
roznice_x = (x - x_mean)
roznice_y = (y - y_mean)
iloczyny = roznice_x * roznice_y
licznik = np.sum(iloczyny)
roznice_x2 = roznice_x**2
roznice_y2 = roznice_y**2
mianownik = np.sqrt(np.sum(roznice_x2))*np.sqrt(np.sum(roznice_y2))
licznik/mianownik

-1.0

In [53]:
def r(x,y):
    x_mean = np.mean(x)
    y_mean = np.mean(y)
    roznice_x = (x - x_mean)
    roznice_y = (y - y_mean)
    iloczyny = roznice_x * roznice_y
    licznik = np.sum(iloczyny)
    roznice_x2 = roznice_x**2
    roznice_y2 = roznice_y**2
    mianownik = np.sqrt(np.sum(roznice_x2))*np.sqrt(np.sum(roznice_y2))
    return licznik/mianownik

In [54]:
def r2(x,y):
    return np.sum((x - np.mean(x)) * (y - np.mean(y)))\
                /(np.sqrt(np.sum((x - np.mean(x))**2))\
                  *np.sqrt(np.sum((y - np.mean(y))**2)))

In [55]:
r(x,y)

-1.0

In [56]:
x = np.random.normal(size=100)
y = 5*x+2
r(x,y)

0.9999999999999997

In [57]:
x = np.random.normal(size=100)
y = np.random.normal(size=100)
r(x,y)

0.01482206615892778

# Zadanie 1.3

In [58]:
np.random.seed(123)
x = np.random.uniform(-3,7,30)

In [59]:
np.mean(x)

1.9830964815049774

In [60]:
np.std(x)

2.2204527447414066

In [61]:
np.sqrt(np.var(x))

2.2204527447414066

In [62]:
nowyX = (x - np.mean(x))/np.std(x)

In [63]:
np.mean(nowyX)

4.810966440042345e-17

In [64]:
np.std(nowyX)

0.9999999999999999

# Zadanie 1.4

In [65]:
x = np.array([1,2,3])
y = np.array([10,100,1000])

In [66]:
np.dot(x,y)

3210

In [67]:
np.matmul(x,y)

3210

In [68]:
x @ y

3210

In [69]:
np.sum(x*y)

3210

In [70]:
x

array([1, 2, 3])

In [71]:
x2D = x.reshape(-1,3)
x2D

array([[1, 2, 3]])

In [72]:
np.matrix.transpose(x2D)

array([[1],
       [2],
       [3]])

In [73]:
np.transpose(x2D)

array([[1],
       [2],
       [3]])

# Zadanie 1.5, 1.6, 1.7

In [74]:
np.random.seed(123)
x = np.random.normal(size=10)
y = x+2

In [75]:
x

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [76]:
rmse = np.sqrt((1/x.size)*np.sum((y-x)**2))
rmse

2.0

In [77]:
rmse = np.sqrt(np.sum((y-x)**2)/x.size)
rmse

2.0

In [78]:
rmse = np.sqrt(np.mean((y-x)**2))
rmse

2.0

In [79]:
def rmse(x,y):
    return np.sqrt(np.mean((y-x)**2))

In [80]:
rmse(x,y)

2.0

In [81]:
def mad(x,y):
    return np.mean(np.abs(x-y))

In [82]:
mad(x,y)

2.0

In [83]:
def madAE(x,y):
    return np.median(np.abs(x-y))

In [84]:
madAE(x,y)

2.0

In [85]:
x = np.random.normal(size=10)
y = x+2
y[0] = x[0]+100

In [86]:
rmse(x,y), mad(x,y), madAE(x,y)

(31.67964646267379, 11.8, 2.0)

# Zadanie 1.8

In [87]:
x = np.array([0,1,0,1,2,3,7])
y = np.array([0,1,1,0,2,4,8])

In [88]:
x != y

array([False, False,  True,  True, False,  True,  True])

In [89]:
np.sum(x != y)

4

In [90]:
np.sum(x != y)/x.size

0.5714285714285714

# Zadanie 1.9

In [91]:
# y = np.array([0,1,0,1,1,1,0])
# y_hat = np.array([])
np.random.seed(123)
y = np.random.randint(0,2,10)
# y = np.random.choice([0,1],10)
y_hat = np.random.uniform(0,1,10)

In [92]:
-np.mean(y*np.log(y_hat)+(1-y)*np.log(1-y_hat))

0.8754414714361378

In [93]:
y

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0])

In [94]:
y

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0])

In [95]:
y_hat = y.copy().astype(float)
y_hat[y_hat==1] = 0.999
y_hat[y_hat==0] = 0.001
# print(y_hat)
-np.mean(y*np.log(y_hat)+(1-y)*np.log(1-y_hat))

0.0010005003335835341

# Zadanie 1.10

In [96]:
x = np.array([1,2,3,4,5])
n = 2

In [97]:
np.NaN

nan

## Dygresja o widokach w numpy i kopiach

In [98]:
def lead(wektor, n):
    # stwórz podwektor [3,4,5]
    y = wektor[n:]
    # stwórz wektor [NaN, NaN]
    nany = np.array([np.NaN] * n) #np.repeat(np.NaN, n)
    # połącz je ze sobą
#     return np.r_[y, nany]
    return np.hstack((y, nany))

In [99]:
np.insert(x, x.size, x)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [100]:
wyjsciowy = lead(x,2)
wyjsciowy[0] = 99
# upewniamy sie, ze wyjsciowy nie ma nic wspolnego z x
wyjsciowy

array([99.,  4.,  5., nan, nan])

In [101]:
x

array([1, 2, 3, 4, 5])

In [102]:
lista1 = [1,2,3,4,5]
lista2 = lista1
lista2[4] = 99
lista1, lista2

([1, 2, 3, 4, 99], [1, 2, 3, 4, 99])

In [103]:
lista1 = [1,2,3,4,5]
lista2 = lista1[1:4]
lista2[2] = 99
lista1, lista2

([1, 2, 3, 4, 5], [2, 3, 99])

In [104]:
lista1 = np.array([1,2,3,4,5])
lista2 = lista1[1:4]
lista2[2] = 99
lista1, lista2

(array([ 1,  2,  3, 99,  5]), array([ 2,  3, 99]))

In [105]:
lista1 = np.array([1,2,3,4,5])
lista2 = lista1[1:4].copy()
lista2[2] = 99
lista1, lista2

(array([1, 2, 3, 4, 5]), array([ 2,  3, 99]))

In [106]:
np.r_[2,3]

array([2, 3])

In [107]:
def lag(wektor, n):
    # stwórz podwektor [3,4,5]
    y = wektor[:(wektor.size-n)]
    # stwórz wektor [NaN, NaN]
    nany = np.array([np.NaN] * n) #np.repeat(np.NaN, n)
    # połącz je ze sobą
#     return np.r_[y, nany]
    return np.insert(nany, nany.size, y)

In [108]:
lag(x,2)

array([nan, nan,  1.,  2.,  3.])

In [109]:
lead(x,2)

array([ 3.,  4.,  5., nan, nan])